import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'
import Header from '../components/Header'
import PostBox from '@/components/PostBox'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <div className='my-7 mx-auto max-w-5xl'>
        <Head>
          <title>Reddit 2</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        {/* PostBox */}
        <PostBox />


        <div>
          {/* Feed */}
        </div>
      </div>
    </>
  )
}
